title: HanpiJoker Blog
iconURL: assets/default-icon.png
remote_theme: supun-io/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: HanpiJoker

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N
