title: HanpiJoker Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: JiahaoSpace
  github: HanpiJoker

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 3868
google_analytics: G-BNEH9TN1JN
